# build smart_nvim docker env

# how to build:
# 1. run :Mason to install lsp servers (optional)
# 2. run :TSInstall <language> to install parsers (optional)
# 3. cp -r ~/.local/share/nvim .
# finally run: docker build --platform=linux/amd64 --network host -f dockerfile/Dockerfile_amd64 .

FROM docker.m.daocloud.io/library/ubuntu:22.04

RUN sed -i s/archive.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list && \
    sed -i s/security.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list

RUN apt-get update

RUN apt-get install -y --no-install-recommends\
      wget \
      git \
      ca-certificates \
      build-essential \
      gcc

# for telescope
RUN apt-get install -y --no-install-recommends\
      ripgrep \
      fd-find \
       && update-ca-certificates

# for some lsp servers
RUN apt-get install -y  --no-install-recommends\
      npm

# for clangd
RUN apt-get install -y  --no-install-recommends\
      bear

# for clipboard
RUN apt-get install -y  --no-install-recommends\
      xclip

# install nvim v0.11.6
RUN wget --no-check-certificate https://github.com/neovim/neovim/releases/download/v0.11.6/nvim-linux-x86_64.tar.gz
RUN tar -zxvf nvim-linux-x86_64.tar.gz
RUN cd nvim-linux-x86_64 && cp -r ./* /usr/local/

# install nvim config & aliases
RUN mkdir ~/.config && cd ~/.config/ \
      && git clone https://github.com/Jiaao-Bai/smart_dotfiles.git \
       && cd smart_dotfiles \
        && mv .config/nvim ~/.config/ \
        && cp .zsh_aliases ~/.zsh_aliases \
        && rm -rf smart_dotfiles

RUN echo "source ~/.zsh_aliases" >> ~/.bashrc

COPY nvim  /root/.local/share/nvim/
